### ISSUE TITLE
Empty message for unauthorized exception

### ISSUE THREAD

**Issue by dextervip** [gliterd/backblaze-b2#17]
Hey,

I have been trying to figure out why I was getting an empty exception. I got that I've used wrong credentials after debugging as the API response below:

string(62) "{
  "code": "unauthorized",
  "message": "",
  "status": 401
}"

So I ended up in ErrorHandler class. I see that unauthorized code is not mapped. And the default exception throws message key from API response which in this case is empty. It would be nice to throw at least the code in case of empty message.

**Comment by mhetreramesh** [comment]
Closed because of inactivity.

**Comment by fozbek** [comment]
This problem is fixed.
https://github.com/gliterd/backblaze-b2/pull/41
