### ISSUE TITLE
Wanting to move from AWS to B2

### ISSUE THREAD

**Issue by circa-one** [gliterd/backblaze-b2#29]
I know this isn't technically an issue, but was wondering if anyone could help me out. I have a website that I made for listing files in a bucket and allowing them to be downloaded, from S3. I'm wanting to move to B2 to save some money and I'm glad a PHP SDK exists, but I'm not a professional web dev, so I'm struggling to understand how to utilize this. It looks similar to the AWS SDK, but integrating it in my web page looks to be different. Here is an example of my existing code:

```
<?php
return [
		's3' => [
			'bucket' => 'gba.circa.im',
			'prefix' => '',
			'version' => 'latest',
			'region' => 'us-east-2',
			'credentials' => array(
				'key' => 'xxx',
				'secret' => 'xxx'
				)
		]
	];
$objects = $s3->getIterator('ListObjects', [
		'Bucket' => $config['s3']['bucket']
	]);
?>
	<?php foreach($objects as $object): ?>

	<li class="block">
		<div class="img gba">&nbsp;</div>
		<a href="<?php echo $s3->getObjectUrl($config['s3']['bucket'], $object['Key']); ?>" class="gba">
		<?php  $link = str_replace('.gba', '', $object['Key']); echo $link; ?>
		</a>
	</li>
```

Particularly the anchor part. I need the file path for the download link, and then the file name as well. Any help? I know it's probably not a good place to ask, but figured I'd start at the source.

**Comment by mhetreramesh** [comment]
You have to do something like:
```
use BackblazeB2\Client;
use BackblazeB2\Bucket;

$options = ['auth_timeout_seconds' => seconds];

$client = new Client('accountId', 'applicationKey', $options);

$fileList = $client->listFiles([
    'BucketId' => 'YOUR_BUCKET_ID'
]);

foreach($fileList as $file) {
    //your logic goes here
}
```

**Comment by mhetreramesh** [comment]
Closing for now.
