### ISSUE TITLE
Backblaze b2 cloud - 503 Service Unavailable error was encountered while trying to upload files like 9GB or more

### ISSUE THREAD

**Issue by showmack3** [gliterd/backblaze-b2#44]
Hi, 

I'm uploading my files in Core Php and Laravel using this repo. But I am always getting 500 or 503 Service Unavailable error was encountered while trying to upload files like 9GB or more. 

Please guide me how to resolve these kind of issues and how to handle if I got these errors...
Because I can not handle the errors like 500 or 503.

Please check the attached screenshot.

![BackBlaze Service Unavailable - 500 or 503 Error while uploading Large Files like 9GB and more](https://user-images.githubusercontent.com/14347711/70593726-1b331180-1c04-11ea-8394-7b75babe0f79.PNG)

Thanks

**Comment by mhetreramesh** [comment]
I've never came across upload large file of that size, I suppose it should be working with function **uploadLargeFile**. 

You should try something like:

```
$file = $client->uploadLargeFile([
    'BucketName' => 'my-special-bucket',
    'FileName' => 'path/to/upload/to',
    'Body' => 'I am the file content'

    // The file content can also be provided via a resource.
    // 'Body' => fopen('/path/to/input', 'r')
]);
```
