### ISSUE TITLE
Harmonize / document exceptions

### ISSUE THREAD

**Issue by BenMorel** [gliterd/backblaze-b2#45]
Hi, I've noticed that methods like `Client::upload()` do not document the exceptions that can be thrown.  At first glance, it looks like these methods may either throw a Guzzle `RequestException` if the request fails, a `B2Exception`, or any other `BackblazeB2\Exceptions\*` exception if the response is a non-`200`.

That makes a lot of potential exceptions that can be thrown, and they do not share a common interface.

Would you be willing to accept a PR to:

- Make all `BackblazeB2\Exceptions\*` exceptions extend `B2Exception`
- Document `Client` methods to throw either a `RequestException` or a `B2Exception`:

```php
    /**
     * Uploads a file to a bucket and returns a File object.
     *
     * @param array $options
     *
     * @return File
     *
     * @throws \GuzzleHttp\Exception\RequestException If the request fails.
     * @throws \BackblazeB2\Exceptions\B2Exception    If the B2 server replies with an error.
     */
    public function upload(array $options)
    {
```

This would work without a BC break, and would make the code more solid, with proper error handling.

**Comment by mhetreramesh** [comment]
@BenMorel I agree we should document the code more with all the possible scenarios. Thanks for the suggestion & off course your PR is very much welcome.

**Comment by BenMorel** [comment]
@mhetreramesh Thank you! #50 waiting for your feedback ;-)

**Comment by mhetreramesh** [comment]
Thank you @BenMorel for the contributions :+1:

**Comment by BenMorel** [comment]
Thank you for the merge, looking forward to the release! 👍
