### ISSUE TITLE
Guzzle v7 interface issue

### ISSUE THREAD

**Issue by kschouw** [gliterd/backblaze-b2#53]
Hi guys,

With the latest commit to the composer file to use Guzzle 6|7 it completely breaks the library unless version 6 is explicitly required before hand. The issue seems to be related to `/Http/Client.php` not conforming to the `Psr\Http\Message\ResponseInterface` in the latest version of Guzzle.

Here is the error when trying to upload something to B2:

```
PHP Fatal error:  Declaration of BackblazeB2\Http\Client::request($method, $uri = NULL, array $options = Array, $asJson = true) must be compatible with GuzzleHttp\Client::request(string $method, $uri = '', array $options = Array): Psr\Http\Message\ResponseInterface in /gliterd/backblaze-b2/src/Http/Client.php on line 43
```

Thanks for the help.

**Comment by mhetreramesh** [comment]
Hi, Thanks for reporting this.

@matthewhall-ca since you sent the PR for this change which was needed for laravel 8. Can you verify if you also has the same issue or works fine?

**Comment by kschouw** [comment]
Thanks @mhetreramesh 

I did a little digging and the Guzzle 7 `request` method on the interface now explicitly requires the `Psr\Http\Message\ResponseInterface` to be returned however a string is returned as the response in `/gliterd/backblaze-b2/src/Http/Client.php`.

**Comment by matthewhall-ca** [comment]
Ah can confirm! I had another package that was locking my laravel to Guzzle 6 so I missed this in my testing! I'll take a look at a new MR that fixes this

**Comment by mhetreramesh** [comment]
I've made a new version with the latest  MR. Thanks for @matthewhall-ca  for the update.

@kschouw you can try with the latest version now, it should be working.
