### ISSUE TITLE
filtering by prefix is missing

### ISSUE THREAD

**Issue by cortesimone** [gliterd/backblaze-b2#64]
Is there a way to use the `$client->listFiles` function filtering by file prefix? I have a bucket with 200k files and I would need to retrieve info only on those belonging to a given directory. 

Thanks, S.

**Comment by mlambley** [comment]
Hi @cortesimone I can see that prefix is implemented in listFiles, eg.
```php
$client->listFiles([
    'Prefix' => $prefix
]);
```

I also just checked the [docs](https://www.backblaze.com/b2/docs/b2_list_file_names.html) and confirmed that we're implementing all of the listFiles features, so please let me know if you have any issues using the prefix parameter.

**Comment by cortesimone** [comment]
Thanks,
it worked

```php
$fileList = $client->listFiles([
    'BucketId' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Prefix' => 'files/b1880106'
]);
```
